language: shell

git:
  depth: 1

os: linux

dist: focal

env:
  - FISH_PPA=nightly-master
  - FISH_PPA=release-3

jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      before_install:
        - brew update
        - brew install fish

before_install:
  - sudo add-apt-repository -y "ppa:fish-shell/$FISH_PPA"
  - sudo apt-get update
  - sudo apt-get -y install fish

before_script:
  - git config --global user.email "tuvistavie+fundle@gmail.com"
  - git config --global user.name "Fundle"
  - fish --version
  - ./install-fishtape.sh

script: fish ./run-tests.fish
